CREATE TABLE IF NOT EXISTS line_comments (
  id INT PRIMARY KEY AUTO_INCREMENT,
  chapterId INT NOT NULL,
  lineNumber INT NOT NULL,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  yorum TEXT NOT NULL,
  isAdmin BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (chapterId) REFERENCES chapters(id) ON DELETE CASCADE
); 